Handle application forms

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -1,6 +1,9 @@
 include ../make/Makefile.inc
 include ../make/Makefile_tex.inc
 
+FILE :=
+GENDER := f
+
 # LATEX_FLAGS := \def\showmargins{}
 
 ## Устав и учредителен протокол
@@ -11,8 +14,31 @@ ngo-creation-docs: $(BUILD_DIR)/creation/устав.pdf $(BUILD_DIR)/creation/у
 # Otherwise there are problems e.g., when filling the application on mobile
 # Requires:
 #   sudo dnf install dejavu-fonts-all
-application-form: | $(BUILD_DIR)
+application-tex: | $(BUILD_DIR)
 	xelatex -output-directory=build заявление_членство.tex
+
+## Show application fields
+application-show:
+	@if [ -z "$(FILE)" ]; then \
+		echo "Error: FILE is not defined. Usage: make application-show FILE=<your_file>"; \
+		exit 1; \
+	fi
+	@uv run --with=pymupdf ../utils/application.py show $(FILE)
+
+## Fill application fields (male)
+application-fill-m: GENDER:=m
+application-fill-m: application-fill
+
+## Fill application fields (female)
+application-fill-f: GENDER:=f
+application-fill-f: application-fill
+
+application-fill:
+	@if [ -z "$(FILE)" ]; then \
+		echo "Error: FILE is not defined. Usage: make application-show FILE=<your_file>"; \
+		exit 1; \
+	fi
+	@uv run --with=pymupdf ../utils/application.py fill -m -g $(GENDER) $(FILE)
 
 clean: ## Clean build directory
 	@rm -rf build
